services:

  app:
    build:
      context: ../
      dockerfile: Containerfile.jvm
    restart: "no"
    hostname: spring-lessons
    environment:
    - TZ=Europe/Rome
    - DEBUG_PORT=5500
    - JAVA_OTHER_OPTIONS=-Dspring.profiles.active=runtime
    - IMPORT_SSL_CERTIFICATE=1
    - REMOTE_SERVICES=google.com:443,webassessor.com:443
    - TRUSTORE_PASSWORD=mypassword
    - RUN_MODE=debug
    - SPRING_APPLICATION_NAME=spring-lessons
    - SPRING_MAIN_BANNER_MODE=off
    - SPRING_MAIN_LOG_STARTUP_INFO=true
    - SPRING_PID_FAIL_IN_WRITE_ERROR=true
    - SERVER_PORT=10000
    - SERVER_SHUTDOWN=graceful
    - SERVER_ERROR_INCLUDE_EXCEPTION=true
    - SERVER_ERROR_INCLUDE_BINDING_ERRORS=always
    - SERVER_ERROR_INCLUDE_MESSAGE=always
    - SERVER_ERROR_INCLUDE_PATH=always
    - SERVER_ERROR_INCLUDE_STACKTRACE=always
    - SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE=20s
    - SPRING_MVC_SERVLET_PATH=/spring-app
    - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
    - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=20MB
    - SPRING_JACKSON_DEFAULT_PROPERTY_INCLUSION=NON_EMPTY
    - SPRING_JACKSON_TIME_ZONE=Europe/Rome
    - MANAGEMENENT_SERVER_PORT=10001
    - MANAGEMENT_SERVER_ADD_APPLICATION_CONTEXT_HEADER=true
    - MANAGEMENT_OBSERVATIONS_ANNOTATIONS_ENABLED=true
    - MANAGEMENT_INFO_ENV_ENABLED=true
    - MANAGEMENT_INFO_JAVA_ENABLED=true
    - MANAGEMENT_INFO_OS_ENABLED=true
    - MANAGEMENT_INFO_PROCESS_ENABLED=true
    - MANAGEMENT_INFO_GIT_MODE=full
    - MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED=true
    - MANAGEMENT_HEALTH_READINESSSTATE_ENABLED=true
    - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,beans,env,health,metrics,prometheus,sbom
    - MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED=true
    - MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://otelcol:4318/v1/metrics
    - MANAGEMENT_OTLP_METRICS_EXPORT_STEP=10s
    - MANAGEMENT_OTLP_TRACING_EXPORT_ENABLED=true
    - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://otelcol:4318/v1/traces
    - MANAGEMENT_OTLP_LOGGING_EXPORT_ENABLED=true
    - MANAGEMENT_OTLP_LOGGING_ENDPOINT=http://otelcol:4318/v1/logs
    - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
    - MANAGEMENT_METRICS_TAGS_ENV=podman
    - SPRING_DATASOURCE_URL=jdbc:postgresql://springdb:5432/spring
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=
    - SPRING_JPA_SHOW_SQL=false
    - SPRING_JPA_OPEN_IN_VIEW=false
    - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
    - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=1000
    - SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS=true
    - SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES=true
    - SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS=false
    - SPRING_FLYWAY_ENABLED=true
    - SPRING_FLYWAY_CONNECT_RETRIES=3
    - SPRING_FLYWAY_CONNECT_RETRIES_INTERVAL=10s
    - SPRING_FLYWAY_VALIDATE_ON_MIGRATE=true
    - SPRING_FLYWAY_DEFAULT_SCHEMA=flyway
    - SPRINGDOC_SHOW_ACTUATOR=true
    - SPRINGDOC_SWAGGER_UI_OPERATIONSSORTED=method
    - SPRINGDOC_SWAGGER_UI_DISPLAY_OPERATION_ID=true
    - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - SPRING_KAFKA_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES=*
    - SPRING_KAFKA_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS=true
    - SPRING_KAFKA_LISTENER_OBSERVATION_ENABLED=true
    - SPRING_KAFKA_TEMPLATE_OBSERVATION_ENABLED=true
    - SPRING_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=false
    - SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS=1
    - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
    - SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER=org.apache.kafka.common.serialization.StringDeserializer
    - SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER=org.springframework.kafka.support.serializer.JsonDeserializer
    - SPRING_KAFKA_PRODUCER_KEY_SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
    - SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER=org.springframework.kafka.support.serializer.JsonSerializer
    - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/master
    - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
    - SPRING_MAIL_HOST=mailpit
    - SPRING_MAIL_PORT=1025
    - SPRING_MAIL_TEST_CONNECTION=true
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=5000
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=3000
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT=5000
    - APP_CONFIG_BASE_DIR=/app/fs
    - APP_CONFIG_CSV_METADATA_COLUMN_SEPARATOR=;
    - APP_CONFIG_CSV_METADATA_QUOTE_CHARACTER='
    - APP_CONFIG_CSV_METADATA_IGNORE_EMPTY_LINES=true
    - APP_CONFIG_CSV_METADATA_STRICT_QUOTE=true
    - APP_CONFIG_CSV_METADATA_APPLY_ALL_QUOTES=true
    - APP_CONFIG_API_DOCUMENTATION_TOKEN_URL=http://keycloak:8080/realms/master/protocol/openid-connect/token
    - APP_CONFIG_API_CLIENT_CONNECTION_REQUEST_TIMEOUT=5
    - APP_CONFIG_API_CLIENT_KEEP_ALIVE=30
    - APP_CONFIG_API_CLIENT_CONNECTION_TIMEOUT=10
    - APP_CONFIG_API_CLIENT_SOCKET_TIMEOUT=60
    - APP_CONFIG_API_CLIENT_TIME_TO_LIVE=60
    - APP_CONFIG_API_CLIENT_MAX_CONN_PER_ROUTE=60
    - APP_CONFIG_API_CLIENT_MAX_CONN_TOTAL=120
    - APP_CONFIG_API_CLIENT_MAX_REDIRECTS=5
    - APP_CONFIG_API_CLIENT_BASE_URL=http://wiremock:8080/wiremock
    - LOG_LEVEL_ROOT=ERROR
    - LOG_LEVEL_COM_PERSONAL_SPRINGLESSONS=TRACE
    - LOG_LEVEL_ORG_SPRINGFRAMEWORK=INFO
    - LOG_LEVEL_ORG_ECLIPSE=ERROR
    - LOG_LEVEL_IO_MICROMETER=ERROR
    - LOG_LEVEL_IO_OPENTELEMETRY=ERROR
    - LOG_LEVEL_ORG_FLYWAYDB=ERROR
    - LOG_LEVEL_ORG_HIBERNATE=ERROR
    ports:
    - "10000:10000" # serve web server
    - "10001:10001" # serve actuator
    - "5500:5500" # serve jdwp
    networks:
    - spring-lessons
    depends_on:
      springdb:
        condition: service_started
      jaeger:
        condition: service_started
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
      otelcol:
        condition: service_started
      kafka:
        condition: service_started
      keycloak:
        condition: service_started
      wiremock:
        condition: service_started
      mailpit:
        condition: service_started
      