apiVersion: 1
datasources:
- name: Jaeger
  type: jaeger
  uid: jaeger_uid
  url: http://jaeger:16686
  editable: true
  isDefault: false
  access: proxy
  jsonData:
    timeout: 60
    tracesToLogsV2:
      datasourceUid: loki_uid
      spanStartTimeShift: 1h
      spanEndTimeShift: -1h
      filterByTraceID: true
      filterBySpanID: true
      customQuery: false
    nodeGraph:
      enabled: true
