apiVersion: 1
datasources:
- name: Loki
  type: loki
  uid: loki_uid
  url: http://loki:3100
  editable: true
  isDefault: true
  jsonData:
    timeout: 60
    maxLines: 1000
    derivedFields:
    - datasourceUid: jaeger_uid
      matcherRegex: '"traceid": "(\w+)"'
      name: TraceID
      url: '$${__value.raw}'
      urlDisplayLabel: 'View Trace'
    - datasourceUid: jaeger_uid
      matcherRegex: '"spanid": "(\w+)"'
      name: SpanID
      url: '$${__value.raw}'
      urlDisplayLabel: 'View Trace'