---
repos:
 - repo: https://github.com/compilerla/conventional-pre-commit
   rev: v4.2.0
   hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args:
       - --verbose
       - --strict
       - --force-scope
       - --scopes=api,setup,docs,tests,deploy
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v6.0.0
   hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-illegal-windows-names
    - id: check-docstring-first
    - id: check-xml
    - id: check-yaml
    - id: check-json
      exclude: '^\.vscode/'
    - id: check-symlinks
    - id: fix-byte-order-marker
    - id: mixed-line-ending
      args:
       - --fix=lf
    - id: pretty-format-json
      args:
       - --autofix
       - --no-sort-keys
       - --indent=4
 - repo: https://github.com/adrienverge/yamllint.git
   rev: v1.37.1
   hooks:
    - id: yamllint
      args:
       - --strict
       - --config-file=.yamllint.yaml
 - repo: local
   hooks:
    - id: maven-validate
      name: Validate Maven project
      entry: mvn validate --file pom.xml --settings settings.xml
      language: system
      pass_filenames: false
      stages: [pre-commit]
    - id: spotless-java
      name: Format Java code with Spotless
      entry: mvn spotless:apply --file pom.xml --settings settings.xml
      language: system
      pass_filenames: false
      stages: [pre-commit]
    - id: compose-validator
      name: Validate Compose Local Application
      language: system
      entry: podman-compose --file ./collections/compose.yaml --file ./collections/compose-app.yaml config
      pass_filenames: false
 - repo: https://github.com/hadolint/hadolint
   rev: v2.14.0
   hooks:
    - id: hadolint
      name: Hadolint
      description: Runs hadolint Docker image to lint Dockerfiles
      entry: podman run --rm --interactive --volume ./:/mnt:ro ghcr.io/hadolint/hadolint hadolint --config /mnt/hadolint.yaml /mnt/Containerfile.jvm
      pass_filenames: false
      language: system
 - repo: https://github.com/koalaman/shellcheck-precommit
   rev: v0.11.0
   hooks:
    - id: shellcheck
      name: entrypoint-shellcheck
      description: Shell script static analysis tool
      entry: podman run --rm --interactive --volume ./:/mnt koalaman/shellcheck:stable entrypoint.sh
      files: entrypoint.sh
      language: system
