FROM eclipse-temurin:21-jre-ubi9-minimal AS runtime
WORKDIR /spring-app
COPY bin/app.jar app.jar
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN groupadd --gid 1000 appgroup \
    && useradd --uid 1000 --gid 1000 --create-home appuser
RUN chmod +x /usr/local/bin/entrypoint.sh
RUN chown appuser:appgroup --recursive /spring-app
USER appuser
ENTRYPOINT ["entrypoint.sh"]
