receivers:
  otlp:
    protocols:
      http:
        endpoint: otelcol:4317
      grpc:
        endpoint: otelcol:4318
processors:
  batch:
exporters:
  logging:
    verbosity: Detailed
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]