services:
  app:
    annotations:
    - topology=application
    - type=spring-boot
    image: spring-lessons:java-latest
    restart: "no"
    container_name: spring-lessons
    environment:
    - TZ=Europe/Rome
    - SPRING_APPLICATION_NAME=spring-lessons
    - SPRING_MAIN_BANNER_MODE=OFF
    - SPRING_MAIN_LOG_STARTUP_INFO=true
    - SERVER_PORT=8080
    - SERVER_SHUTDOWN=graceful
    - SERVER_ERROR_INCLUDE_EXCEPTION=true
    - SERVER_ERROR_INCLUDE_BINDING_ERRORS=on-param
    - SERVER_ERROR_INCLUDE_PATH=on-param
    - SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE=20s
    - SPRING_MVC_SERVLET_PATH=/spring-app
    - MANAGEMENENT_SERVER_PORT=8081
    - MANAGEMENT_OBSERVATIONS_ANNOTATIONS_ENABLED=true
    - MANAGEMENT_INFO_ENV_ENABLED=true
    - MANAGEMENT_INFO_JAVA_ENABLED=true
    - MANAGEMENT_INFO_OS_ENABLED=true
    - MANAGEMENT_INFO_PROCESS_ENABLED=true
    - MANAGEMENT_INFO_GIT_MODE=full
    - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,beans,env,health,metrics,prometheus
    - MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://otel-col:4318/v1/metrics
    - MANAGEMENT_OTLP_METRICS_EXPORT_STEP=10s
    - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://otel-col:4318/v1/traces
    - MANAGEMENT_OTLP_LOGGING_ENDPOINT=http://otel-col:4317
    - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
    - MANAGEMENT_METRICS_TAGS_ENV=runtime
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/spring
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=adminpwd
    - SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY=SELECT 1
    - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    - SPRING_JPA_SHOW_SQL=false
    - SPRING_JPA_OPEN_IN_VIEW=false
    - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
    - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    - SPRING_FLYWAY_ENABLED=true
    - SPRING_FLYWAY_CONNECT_RETRIES=3
    - SPRING_FLYWAY_CONNECT_RETRIES_INTERVAL=10s
    - SPRING_FLYWAY_VALUDATE_ON_MIGRATE=true
    - SPRING_FLYWAY_DEFAULT_SCHEMA=flyway
    - APP_CONFIG_DEFAULT_PATH=/tmp/fs
    - JAVA_OTHER_OPTIONS=-Dspring.profiles.active=runtime
    ports:
    - "8080:8080" # serve web server
    - "8081:8081" # serve actuator
    networks:
    - development
    
networks:
  development:
    name: development
    driver: bridge