{
 "title": "HTTP Services",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Jetty Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jetty_threads_idle{exported_job=\"spring-lessons\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(jetty_threads_busy{exported_job=\"spring-lessons\"})",
     "legendFormat": "Working"
    },
    {
     "expr": "sum(jetty_threads_jobs{exported_job=\"spring-lessons\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(jetty_connections_current{exported_job=\"spring-lessons\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "HTTP Clients Status Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri, status) (increase(http_client_requests_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server Status Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri, status) (increase(http_server_requests_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}