receivers:
  otlp:
    protocols:
      http:
        endpoint: otelcol:4318
        cors:
          allowed_origins:
          - "http://*"
          - "https://*"
      grpc:
        endpoint: otelcol:4317

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: otelcol:8889
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true
      level: true
      instance: true
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:
  
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]