receivers:
  otlp:
    protocols:
      http:
        endpoint: otelcol:4318
        cors:
          allowed_origins:
          - "http://*"
          - "https://*"
      grpc:
        endpoint: otelcol:4317

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: otelcol:8889
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:
  
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]