FROM docker.io/library/maven:3.9.6-eclipse-temurin-17

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid "$USER_GID" "$USERNAME" \
    && useradd --uid "$USER_UID" --gid "$USER_GID" --create-home "$USERNAME"

USER "$USERNAME"
WORKDIR /workspace