CREATE USER grafanareader WITH PASSWORD '';
GRANT CONNECT ON DATABASE SPRING TO grafanareader;
GRANT USAGE ON SCHEMA SPRING_APP TO grafanareader;
GRANT SELECT ON ALL TABLES IN SCHEMA SPRING_APP TO grafanareader;
ALTER DEFAULT PRIVILEGES IN SCHEMA SPRING_APP GRANT SELECT ON TABLES TO grafanareader;
